// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOdj0y9oPROUgxkfKUzyB-fkYjEoKW24',
    appId: '1:197399109297:web:d453b9eb7a022d68ebcc90',
    messagingSenderId: '197399109297',
    projectId: 'guardtrack-8f613',
    authDomain: 'guardtrack-8f613.firebaseapp.com',
    storageBucket: 'guardtrack-8f613.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWnH0uvSiNOrbIvqSLgCfTr8Nq1CiwLIM',
    appId: '1:197399109297:android:969c89bf037f00f8ebcc90',
    messagingSenderId: '197399109297',
    projectId: 'guardtrack-8f613',
    storageBucket: 'guardtrack-8f613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_V5gO0ZFp9dEp93GF2lwpc-K6Py4QxYE',
    appId: '1:197399109297:ios:5b5a7031f0a2ce40ebcc90',
    messagingSenderId: '197399109297',
    projectId: 'guardtrack-8f613',
    storageBucket: 'guardtrack-8f613.firebasestorage.app',
    iosBundleId: 'com.guardtrack.guardMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_V5gO0ZFp9dEp93GF2lwpc-K6Py4QxYE',
    appId: '1:197399109297:ios:5b5a7031f0a2ce40ebcc90',
    messagingSenderId: '197399109297',
    projectId: 'guardtrack-8f613',
    storageBucket: 'guardtrack-8f613.firebasestorage.app',
    iosBundleId: 'com.guardtrack.guardMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMOdj0y9oPROUgxkfKUzyB-fkYjEoKW24',
    appId: '1:197399109297:web:75edca13109d9a18ebcc90',
    messagingSenderId: '197399109297',
    projectId: 'guardtrack-8f613',
    authDomain: 'guardtrack-8f613.firebaseapp.com',
    storageBucket: 'guardtrack-8f613.firebasestorage.app',
  );
}
